from random import Random

from src.random_class import RandomGenerator

DISTANCE_REGULATOR = 100
DAYS_OF_MEMORY = 20

NO_CIRCUITS = 50
NO_THERMOELECTRICS = 8

MIN_CITIZEN = 600
MAX_CITIZEN = 5000
MAX_DEVIATION_CITIZEN_IN_BLOCK = 200

DEMAND_PER_PERSON = 0.005
DEMAND_INDUSTRIALIZATION = 10

VARIABILITY_DEMAND_PER_PERSON = 1e-3
VARIABILITY_DEMAND_PER_INDUSTRIALIZATION = 6

PEAK_CONSUMPTION_MORNING = 7
PEAK_CONSUMPTION_EVENING = 19

MAX_DEVIATION_MORNING = 1
MAX_DEVIATION_EVENING = 2

WEIGHT_MORNING = 10
WEIGHT_EVENING = 20


RANDOM_SEED = 13
RANDOM = RandomGenerator(45, 13)  # 4806545

MIN_BLOCKS_PER_CIRCUIT = 1
MAX_BLOCKS_PER_CIRCUIT = 5

K_PREDICT_CONSUMPTION_ITER = 300

# CHIEF PARAMS
IMPORTANCE_ALPHA = 0.374345
OBJECTIVE_FUNCTION_INTENTION_PARAMS_WEIGHT = 5
OBJECTIVE_FUNCTION_INTENTION_PARAMS_DEFAULT_WEIGHT = 1


# PARTS

BOILER_PART_WEIBULL_SHAPE_MIN = 1
BOILER_PART_WEIBULL_SHAPE_MAX = BOILER_PART_WEIBULL_SHAPE_MIN + 1e-3

BOILER_PART_WEIBULL_SCALE_MIN = 40
BOILER_PART_WEIBULL_SCALE_MAX = 70

BOILER_PART_LOGNORMAL_MEAN_MIN = 2.5
BOILER_PART_LOGNORMAL_MEAN_MAX = 3

BOILER_PART_LOGNORMAL_DEVIATION_MIN = 0.3
BOILER_PART_LOGNORMAL_DEVIATION_MAX = 4


def boiler_amount_for_capacity(capacity: float) -> int:
    if capacity < 6000:
        return 1
    if capacity < 15000:
        return 2
    if capacity < 30000:
        return 3
    return 4


COILS_PART_WEIBULL_SHAPE_MIN = 1
COILS_PART_WEIBULL_SHAPE_MAX = COILS_PART_WEIBULL_SHAPE_MIN

COILS_PART_WEIBULL_SCALE_MIN = 80
COILS_PART_WEIBULL_SCALE_MAX = 120

COILS_PART_LOGNORMAL_MEAN_MIN = 2.5
COILS_PART_LOGNORMAL_MEAN_MAX = 3

COILS_PART_LOGNORMAL_DEVIATION_MIN = 0.3
COILS_PART_LOGNORMAL_DEVIATION_MAX = 4


STEAM_TURBINE_PART_WEIBULL_SHAPE_MIN = 1
STEAM_TURBINE_PART_WEIBULL_SHAPE_MAX = STEAM_TURBINE_PART_WEIBULL_SHAPE_MIN + 1e-4

STEAM_TURBINE_PART_WEIBULL_SCALE_MIN = 80
STEAM_TURBINE_PART_WEIBULL_SCALE_MAX = 120

STEAM_TURBINE_PART_LOGNORMAL_MEAN_MIN = 2.5
STEAM_TURBINE_PART_LOGNORMAL_MEAN_MAX = 3

STEAM_TURBINE_PART_LOGNORMAL_DEVIATION_MIN = 0.3
STEAM_TURBINE_PART_LOGNORMAL_DEVIATION_MAX = 4


GENERATOR_PART_WEIBULL_SHAPE_MIN = 1
GENERATOR_PART_WEIBULL_SHAPE_MAX = GENERATOR_PART_WEIBULL_SHAPE_MIN + 1e-4

GENERATOR_PART_WEIBULL_SCALE_MIN = 80
GENERATOR_PART_WEIBULL_SCALE_MAX = 120

GENERATOR_PART_LOGNORMAL_MEAN_MIN = 2.5
GENERATOR_PART_LOGNORMAL_MEAN_MAX = 3

GENERATOR_PART_LOGNORMAL_DEVIATION_MIN = 0.3
GENERATOR_PART_LOGNORMAL_DEVIATION_MAX = 4


HURRY_REPAIR_ALPHA = 0.4
