DISTANCE_REGULATOR = 0.5
DAYS_OF_MEMORY = 20

OBJECTIVE_FUNCTION_INTENTION_PARAMS_WEIGHT = 5
OBJECTIVE_FUNCTION_INTENTION_PARAMS_DEFAULT_WEIGHT = 1

K_PREDICT_CONSUMPTION_ITER = 300

NO_CIRCUITS = 50
NO_THERMOELECTRICS = 8

MIN_CITIZEN = 1000
MAX_CITIZEN = 10000
MAX_DEVIATION_CITIZEN_IN_BLOCK = 200

DEMAND_PER_PERSON = 1
DEMAND_INDUSTRIALIZATION = 5000

VARIABILITY_DEMAND_PER_PERSON = 0.01
VARIABILITY_DEMAND_PER_INDUSTRIALIZATION = 100

PEAK_CONSUMPTION_MORNING = 7
PEAK_CONSUMPTION_EVENING = 19

MAX_DEVIATION_MORNING = 2
MAX_DEVIATION_EVENING = 3

WEIGHT_MORNING = 10
WEIGHT_EVENING = 20

RANDOM_SEED = 42

MIN_BLOCKS_PER_CIRCUIT = 1
MAX_BLOCKS_PER_CIRCUIT = 10

# CHIEF PARAMS
IMPORTANCE_ALPHA = 0.374345